### PR TITLE
feat(core): watch multinamespace

### PR DESCRIPTION
**Pull request by hbradfield**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42263

### CODE REVIEW

**Review by lauriet-ibm — APPROVED** [review]
~/lgtm~

**Comment by hbradfield** [comment]
Testing results, may have found bug in namespace scope operator. Jiaming is investigating:

The namespace scope operator restarted my operator pod, but now it's looking for a rbac that has a different name than what the namespace scope operator created:
```
E1103 14:50:09.605898       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.CommonAudit: commonaudits.operator.ibm.com is forbidden: User "system:serviceaccount:ibm-common-services:ibm-auditlogging-operator" cannot list resource "commonaudits" in API group "operator.ibm.com" in the namespace "test": RBAC: role.rbac.authorization.k8s.io "namespacescope-managed-role-from-ibm-common-services" not found
➜  ~ oc get role
NAME                                                                  AGE
audit-logging-fluentd-ds-role                                         4m57s
ibm-auditlogging-cleanup                                              5m22s
ibm-auditlogging-operator                                             5m22s
ibm-common-service-operator.v3.6.0-ljwfz                              15m
ibm-common-service-webhook                                            28m
ibm-namespace-scope-operator                                          28m
leader-election-role                                                  5m20s
namespacescope-managed-role-from-ibm-common-services-common-service   15m
operand-deployment-lifecycle-manager.v1.4.0-7ghpd                     15m
➜  ~ oc get role -n test
NAME                                                                  AGE
namespace-scope-role                                                  6m16s
namespacescope-managed-role-from-ibm-common-services-common-service   106s

**Comment by hbradfield** [comment]
Need to create a custom cache
```
2020-11-03T16:28:33.530Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "operator.ibm.com", "reconcilerKind": "AuditLogging", "controller": "auditlogging", "name": "example-auditlogging", "namespace": "", "error": "unable to get: /example-auditlogging because of unknown namespace for the cache"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90
```
https://github.com/kubernetes-sigs/controller-runtime/issues/934

**Review by horis233 — COMMENTED** [review]
/lgtm

**Comment by hbradfield** [comment]
will start testing upgrade

**Pull request merged**
