### PR TITLE
fix(dockerfile): update to ubi8 min 3-230

### PR DESCRIPTION
**Pull request by hbradfield**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43390

### CODE REVIEW

**Comment by znhafeez** [comment]
I forget, does the operator CSV need to be bumped up as well?

**Comment by hbradfield** [comment]
@znhafeez yup I forgot thanks haha, will fix

**Comment by znhafeez** [comment]
No worries, I. wasn't 100% sure myself!

**Review by znhafeez — APPROVED** [review]
lgtm

**Pull request merged**
