### PR TITLE
refactor(core): migrate to Kubebuilder-style layout

### PR DESCRIPTION
**Pull request by hbradfield**
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41448

### CODE REVIEW

**Comment by horis233** [comment]
Hi @hbradfield, this PR looks good for me.

There is only one point I want to suggest.

For the `leader_election_role_binding`,  if we bind it to SA `ibm-auditlogging-operator` as you did for the role binding, then these roles and rolebindings wouldn't be added into the bundle directory. 

https://github.com/IBM/ibm-auditlogging-operator/blob/opsdk-v1/config/rbac/leader_election_role_binding.yaml#L11

You can update the SA in the above file and delete the bundle folder and use `make generate-all` to re-generate the bundle.

I just found this today. I think only the roles and rolebindings for the other service accounts, except for the operator service account, will be added into the `bundle/manifests` folder.

**Comment by horis233** [comment]
@hbradfield Thanks for your update, it looks good for me now.

**Comment by hbradfield** [comment]
@lauriet-ibm my cluster just went down, and i need to bundle this new image/create another catalog when i get a new one. ill probably have it tested by tmrw fyi, so ill give the green light once i get that up and tested

**Comment by hbradfield** [comment]
successful test of bundle/catalog image

**Comment by hbradfield** [comment]
@lauriet-ibm ready for review

**Review by lauriet-ibm — APPROVED** [review]
Leisa indicated the csv should show the Maintainers like this
 maintainers:
  - email: https://www.ibm.com/mysupport/
    name: IBM Support

**Pull request merged**
